[2020-10-28 09:57:01,919] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-10-28 09:57:02,036] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2499
[2020-10-28 09:57:02,198] [base.py:93] [base:get_response] [WARNING]- Not Found: /favicon.ico
[2020-10-28 09:57:02,199] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 2191
[2020-10-28 09:57:10,479] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 200 4329
[2020-10-28 09:57:10,513] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2799
[2020-10-28 09:57:19,784] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 200 4341
[2020-10-28 09:57:19,817] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2770
[2020-10-28 09:57:26,383] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw?ran=0.2435597673316523 HTTP/1.1" 200 2530
[2020-10-28 09:57:31,258] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-10-28 09:57:31,274] [views.py:23] [views:index] [INFO]- 缓存中的key为：df0249b618c011eb8b8a5800e3fb0696----浏览器中的key为:df0249b618c011eb8b8a5800e3fb0696
[2020-10-28 09:57:31,439] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 17963
[2020-10-28 09:57:31,475] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/58950l.jpg HTTP/1.1" 304 0
[2020-10-28 09:57:31,476] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/58950l_O9lXQZR.jpg HTTP/1.1" 304 0
[2020-10-28 09:57:31,479] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/58950l_5kfSspN.jpg HTTP/1.1" 304 0
[2020-10-28 09:57:31,488] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/57304l.jpg HTTP/1.1" 304 0
[2020-10-28 09:57:31,490] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/57840l.jpg HTTP/1.1" 304 0
[2020-10-28 09:57:31,497] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/59178l.jpg HTTP/1.1" 304 0
[2020-10-28 09:57:31,502] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/banner/8797s.jpg HTTP/1.1" 304 0
[2020-10-28 09:57:31,503] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/banner/57304l.jpg HTTP/1.1" 304 0
[2020-10-28 09:57:37,338] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7661
[2020-10-28 10:00:10,440] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7688
[2020-10-28 10:00:11,661] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7688
[2020-10-28 10:01:23,314] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7718
[2020-10-28 10:01:24,442] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/1111 HTTP/1.1" 200 8273
[2020-10-28 10:01:24,463] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/novels/58950l.jpg HTTP/1.1" 304 0
[2020-10-28 10:01:47,416] [base.py:93] [base:get_response] [WARNING]- Not Found: /delbookcase/2718.php
[2020-10-28 10:01:47,418] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /delbookcase/2718.php HTTP/1.1" 404 2218
[2020-10-28 10:02:05,726] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/logout HTTP/1.1" 302 0
[2020-10-28 10:02:05,736] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-10-28 10:02:05,771] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2290
[2020-10-28 10:02:08,912] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/register HTTP/1.1" 200 5843
[2020-10-28 10:02:57,565] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/register HTTP/1.1" 200 5838
[2020-10-28 10:03:00,703] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/register HTTP/1.1" 200 5838
[2020-10-28 10:03:12,107] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/send_code?phone=15810868968 HTTP/1.1" 200 53
[2020-10-28 10:03:33,163] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /user/register
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Envs\Django2020\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "D:\Envs\Django2020\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "D:\Envs\Django2020\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "D:\Envs\Django2020\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry '15810868968' for key 'user.phone_num'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\user\views.py", line 88, in user_register
    user = User.objects.create(uid=uid, username=username, password=password, email=email, phone_num=phone)
  File "D:\Envs\Django2020\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Envs\Django2020\lib\site-packages\django\db\models\query.py", line 417, in create
    obj.save(force_insert=True, using=self.db)
  File "D:\Envs\Django2020\lib\site-packages\django\contrib\auth\base_user.py", line 73, in save
    super().save(*args, **kwargs)
  File "D:\Envs\Django2020\lib\site-packages\django\db\models\base.py", line 729, in save
    force_update=force_update, update_fields=update_fields)
  File "D:\Envs\Django2020\lib\site-packages\django\db\models\base.py", line 759, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "D:\Envs\Django2020\lib\site-packages\django\db\models\base.py", line 842, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "D:\Envs\Django2020\lib\site-packages\django\db\models\base.py", line 880, in _do_insert
    using=using, raw=raw)
  File "D:\Envs\Django2020\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Envs\Django2020\lib\site-packages\django\db\models\query.py", line 1125, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "D:\Envs\Django2020\lib\site-packages\django\db\models\sql\compiler.py", line 1280, in execute_sql
    cursor.execute(sql, params)
  File "D:\Envs\Django2020\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "D:\Envs\Django2020\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\Envs\Django2020\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Envs\Django2020\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Envs\Django2020\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Envs\Django2020\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Envs\Django2020\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "D:\Envs\Django2020\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "D:\Envs\Django2020\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "D:\Envs\Django2020\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1062, "Duplicate entry '15810868968' for key 'user.phone_num'")
[2020-10-28 10:03:33,340] [basehttp.py:124] [basehttp:log_message] [ERROR]- "POST /user/register HTTP/1.1" 500 202841
[2020-10-28 10:04:09,762] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /user/register
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Envs\Django2020\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "D:\Envs\Django2020\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "D:\Envs\Django2020\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "D:\Envs\Django2020\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry '15810868968' for key 'user.phone_num'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\user\views.py", line 88, in user_register
    user = User.objects.create(uid=uid, username=username, password=password, email=email, phone_num=phone)
  File "D:\Envs\Django2020\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Envs\Django2020\lib\site-packages\django\db\models\query.py", line 417, in create
    obj.save(force_insert=True, using=self.db)
  File "D:\Envs\Django2020\lib\site-packages\django\contrib\auth\base_user.py", line 73, in save
    super().save(*args, **kwargs)
  File "D:\Envs\Django2020\lib\site-packages\django\db\models\base.py", line 729, in save
    force_update=force_update, update_fields=update_fields)
  File "D:\Envs\Django2020\lib\site-packages\django\db\models\base.py", line 759, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "D:\Envs\Django2020\lib\site-packages\django\db\models\base.py", line 842, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "D:\Envs\Django2020\lib\site-packages\django\db\models\base.py", line 880, in _do_insert
    using=using, raw=raw)
  File "D:\Envs\Django2020\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Envs\Django2020\lib\site-packages\django\db\models\query.py", line 1125, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "D:\Envs\Django2020\lib\site-packages\django\db\models\sql\compiler.py", line 1280, in execute_sql
    cursor.execute(sql, params)
  File "D:\Envs\Django2020\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "D:\Envs\Django2020\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\Envs\Django2020\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Envs\Django2020\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Envs\Django2020\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Envs\Django2020\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Envs\Django2020\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "D:\Envs\Django2020\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "D:\Envs\Django2020\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "D:\Envs\Django2020\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1062, "Duplicate entry '15810868968' for key 'user.phone_num'")
[2020-10-28 10:04:09,854] [basehttp.py:124] [basehttp:log_message] [ERROR]- "POST /user/register HTTP/1.1" 500 202842
[2020-10-28 10:04:26,474] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/register HTTP/1.1" 200 12
[2020-10-28 10:04:32,601] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/register HTTP/1.1" 200 5838
[2020-10-28 10:04:34,677] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-10-28 10:04:34,710] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2408
[2020-10-28 10:04:48,626] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 200 4329
[2020-10-28 10:04:48,662] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2631
[2020-10-28 10:05:02,208] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-10-28 10:05:02,226] [views.py:23] [views:index] [INFO]- 缓存中的key为：ecdfae3018c111ebbd0a5800e3fb0696----浏览器中的key为:ecdfae3018c111ebbd0a5800e3fb0696
[2020-10-28 10:05:02,293] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 17964
[2020-10-28 10:05:04,048] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6258
[2020-10-28 10:05:38,995] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6212
[2020-10-28 10:05:40,050] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6212
[2020-10-28 10:06:37,439] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6213
[2020-10-28 10:06:38,816] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6213
[2020-10-28 10:06:39,144] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6213
[2020-10-28 10:06:39,325] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 6213
[2020-10-28 10:06:41,572] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/logout HTTP/1.1" 302 0
[2020-10-28 10:06:41,581] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-10-28 10:06:41,614] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2537
[2020-10-28 10:06:47,140] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw?ran=0.47305297358158094 HTTP/1.1" 200 2647
[2020-10-28 10:06:52,755] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-10-28 10:06:52,770] [views.py:23] [views:index] [INFO]- 缓存中的key为：3883abbe18c211eb8cb45800e3fb0696----浏览器中的key为:3883abbe18c211eb8cb45800e3fb0696
[2020-10-28 10:06:52,835] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 17963
[2020-10-28 10:06:54,409] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7705
[2020-10-28 10:09:03,923] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7669
[2020-10-28 10:09:04,798] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7669
[2020-10-28 10:09:05,197] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7669
[2020-10-28 10:09:05,415] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7669
[2020-10-28 10:09:41,353] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7699
[2020-10-28 10:09:43,693] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7699
[2020-10-28 10:39:59,029] [views.py:23] [views:index] [INFO]- 缓存中的key为：None----浏览器中的key为:3883abbe18c211eb8cb45800e3fb0696
[2020-10-28 10:39:59,045] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 302 0
[2020-10-28 10:39:59,065] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-10-28 10:39:59,105] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2687
[2020-10-28 10:40:07,992] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 200 4341
[2020-10-28 10:40:08,045] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2828
[2020-10-28 10:40:15,870] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 200 4341
[2020-10-28 10:40:15,916] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2659
[2020-10-28 10:40:28,119] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-10-28 10:40:28,138] [views.py:23] [views:index] [INFO]- 缓存中的key为：df1b747e18c611ebb82c5800e3fb0696----浏览器中的key为:df1b747e18c611ebb82c5800e3fb0696
[2020-10-28 10:40:28,379] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 17963
[2020-10-28 10:43:53,451] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7691
[2020-10-28 13:39:27,396] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/121212121212 HTTP/1.1" 200 8634
[2020-10-28 13:39:27,415] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/novels/57304l.jpg HTTP/1.1" 304 0
[2020-10-28 13:39:41,566] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/add_bookrack?novelUid=121212121212 HTTP/1.1" 200 17
[2020-10-28 13:39:45,830] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/novelbody/111111 HTTP/1.1" 200 13481
[2020-10-28 13:39:48,373] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/add_chapter?chapterUid=111111 HTTP/1.1" 200 17
[2020-10-28 13:39:51,600] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8441
[2020-10-28 13:42:17,387] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8427
[2020-10-28 13:42:18,145] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8427
[2020-10-28 13:43:46,058] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8439
[2020-10-28 13:43:46,909] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8439
[2020-10-28 13:44:17,386] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8427
[2020-10-28 13:44:18,023] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8427
[2020-10-28 13:45:14,428] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8373
[2020-10-28 13:45:15,188] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8373
[2020-10-28 13:48:25,217] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8387
[2020-10-28 13:49:03,164] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8379
[2020-10-28 13:49:03,919] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8379
[2020-10-28 13:49:04,169] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8379
[2020-10-28 13:49:04,382] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8379
[2020-10-28 13:50:48,641] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/show_bookrack
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 108, in show_bookrack
    return render(request, 'novel/show_bookrack.html', locals())
  File "D:\Envs\Django2020\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Envs\Django2020\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Envs\Django2020\lib\site-packages\django\urls\base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Envs\Django2020\lib\site-packages\django\urls\resolvers.py", line 632, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '(None,)' not found. 1 pattern(s) tried: ['novels\\/detail\\/(?P<gid>[0-9]+)$']
[2020-10-28 13:50:48,799] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/show_bookrack HTTP/1.1" 500 185134
[2020-10-28 13:51:27,158] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/novelbody/111111 HTTP/1.1" 200 13481
[2020-10-28 13:51:31,161] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8262
[2020-10-28 13:59:47,774] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8262
[2020-10-28 13:59:51,742] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/121212121212 HTTP/1.1" 200 8634
[2020-10-28 13:59:54,214] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/novelbody/333333
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 77, in novel_body
    with open(file_name, encoding='utf-8') as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\novels\\333333.txt'
[2020-10-28 13:59:54,273] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/novelbody/333333 HTTP/1.1" 500 75758
[2020-10-28 14:00:01,339] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/novelbody/232311111
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 77, in novel_body
    with open(file_name, encoding='utf-8') as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\novels\\232311111.txt'
[2020-10-28 14:00:01,395] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/novelbody/232311111 HTTP/1.1" 500 75818
[2020-10-28 14:00:04,824] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/novelbody/232311111
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 77, in novel_body
    with open(file_name, encoding='utf-8') as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\novels\\232311111.txt'
[2020-10-28 14:00:04,878] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/novelbody/232311111 HTTP/1.1" 500 75818
[2020-10-28 14:00:37,642] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/121212121212 HTTP/1.1" 200 8634
[2020-10-28 14:00:38,998] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/novelbody/232311111 HTTP/1.1" 200 13901
[2020-10-28 14:00:40,940] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/add_chapter?chapterUid=232311111 HTTP/1.1" 200 17
[2020-10-28 14:00:44,779] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8958
[2020-10-28 14:04:21,196] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8958
[2020-10-28 14:04:22,345] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8958
[2020-10-28 14:04:32,685] [views.py:23] [views:index] [INFO]- 缓存中的key为：None----浏览器中的key为:df1b747e18c611ebb82c5800e3fb0696
[2020-10-28 14:04:32,695] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 302 0
[2020-10-28 14:04:32,708] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-10-28 14:04:32,744] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2903
[2020-10-28 14:04:42,140] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-10-28 14:04:42,156] [views.py:23] [views:index] [INFO]- 缓存中的key为：72c4ed4c18e311eba4965800e3fb0696----浏览器中的key为:72c4ed4c18e311eba4965800e3fb0696
[2020-10-28 14:04:42,225] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 17963
[2020-10-28 14:04:44,666] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/1111 HTTP/1.1" 200 8273
[2020-10-28 14:04:47,243] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/novelbody/44444444 HTTP/1.1" 200 13572
[2020-10-28 14:04:48,520] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/add_chapter?chapterUid=44444444 HTTP/1.1" 200 17
[2020-10-28 14:04:53,809] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 9660
[2020-10-28 14:05:00,482] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/121212121212 HTTP/1.1" 200 8634
[2020-10-28 14:05:02,763] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/novelbody/333333
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 77, in novel_body
    with open(file_name, encoding='utf-8') as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\novels\\333333.txt'
[2020-10-28 14:05:02,815] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/novelbody/333333 HTTP/1.1" 500 75758
[2020-10-28 14:05:25,768] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/121212121212 HTTP/1.1" 200 8634
[2020-10-28 14:05:26,724] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/novelbody/333333 HTTP/1.1" 200 13508
[2020-10-28 14:05:28,077] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/add_chapter?chapterUid=333333 HTTP/1.1" 200 17
[2020-10-28 14:05:40,715] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 10353
[2020-10-28 14:07:19,560] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/add_chapter?chapterUid=333333 HTTP/1.1" 200 17
[2020-10-28 14:07:53,093] [base.py:93] [base:get_response] [WARNING]- Not Found: /novels/novelbody/107254.html
[2020-10-28 14:07:53,094] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /novels/novelbody/107254.html HTTP/1.1" 404 3611
[2020-10-28 14:07:57,037] [base.py:93] [base:get_response] [WARNING]- Not Found: /0/111/
[2020-10-28 14:07:57,038] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /0/111/ HTTP/1.1" 404 2176
[2020-10-28 14:08:01,880] [views.py:23] [views:index] [INFO]- 缓存中的key为：72c4ed4c18e311eba4965800e3fb0696----浏览器中的key为:72c4ed4c18e311eba4965800e3fb0696
[2020-10-28 14:08:02,058] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 17963
[2020-10-28 14:08:05,215] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/11111111 HTTP/1.1" 200 7921
[2020-10-28 14:08:05,241] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/novels/8797s.jpg HTTP/1.1" 304 0
[2020-10-28 14:08:12,546] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/11111111 HTTP/1.1" 200 7921
[2020-10-28 14:08:18,913] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/add_bookrack?novelUid=11111111 HTTP/1.1" 200 17
[2020-10-28 14:08:23,193] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 11051
[2020-10-28 14:08:33,230] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/add_bookrack?novelUid=11111111 HTTP/1.1" 200 17
[2020-10-28 14:09:25,973] [views.py:23] [views:index] [INFO]- 缓存中的key为：72c4ed4c18e311eba4965800e3fb0696----浏览器中的key为:72c4ed4c18e311eba4965800e3fb0696
[2020-10-28 14:09:26,058] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 17963
[2020-10-28 14:09:30,029] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/121212121212 HTTP/1.1" 200 8634
[2020-10-28 14:09:32,888] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/novelbody/232311111 HTTP/1.1" 200 13901
[2020-10-28 14:09:35,174] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/add_chapter?chapterUid=232311111 HTTP/1.1" 200 17
[2020-10-28 14:09:42,278] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/add_chapter?chapterUid=232311111 HTTP/1.1" 200 17
[2020-10-28 14:09:44,545] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 11051
[2020-10-28 14:10:27,667] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8969
[2020-10-28 14:10:36,632] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/121212121212 HTTP/1.1" 200 8634
[2020-10-28 14:10:39,966] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/novelbody/111111 HTTP/1.1" 200 13484
[2020-10-28 14:10:41,321] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/add_chapter?chapterUid=111111 HTTP/1.1" 200 17
[2020-10-28 14:10:45,652] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/novelbody/232311111 HTTP/1.1" 200 13901
[2020-10-28 14:10:46,696] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/add_chapter?chapterUid=232311111 HTTP/1.1" 200 17
[2020-10-28 14:10:51,116] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 10358
[2020-10-28 14:12:08,511] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/121212121212 HTTP/1.1" 200 8634
[2020-10-28 14:12:10,805] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/novelbody/333333 HTTP/1.1" 200 13508
[2020-10-28 14:12:12,072] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/add_chapter?chapterUid=333333 HTTP/1.1" 200 17
[2020-10-28 14:16:36,393] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/novelbody/333333 HTTP/1.1" 200 13508
[2020-10-28 14:18:56,974] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/121212121212 HTTP/1.1" 200 8634
[2020-10-28 14:18:58,915] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 11051
[2020-10-28 14:19:23,646] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8969
[2020-10-28 14:19:25,790] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/121212121212 HTTP/1.1" 200 8634
[2020-10-28 14:19:27,927] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/novelbody/111111 HTTP/1.1" 200 13484
[2020-10-28 14:19:29,136] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/add_chapter?chapterUid=111111 HTTP/1.1" 200 17
[2020-10-28 14:19:31,410] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8975
[2020-10-28 14:19:35,058] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/121212121212 HTTP/1.1" 200 8634
[2020-10-28 14:19:36,597] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/novelbody/333333 HTTP/1.1" 200 13508
[2020-10-28 14:19:37,728] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/add_chapter?chapterUid=333333 HTTP/1.1" 200 17
[2020-10-28 14:19:40,291] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8975
[2020-10-28 14:26:13,273] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/novelbody/232311111 HTTP/1.1" 200 13901
[2020-10-28 14:26:14,987] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/add_chapter?chapterUid=232311111 HTTP/1.1" 200 17
[2020-10-28 15:16:16,640] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/novelbody/232311111 HTTP/1.1" 200 13901
[2020-10-28 15:16:19,090] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/show_bookrack
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 129, in show_bookrack
    mybookrack = MyBookrack.objects.filter(user_id=user.uid).all()
AttributeError: 'NoneType' object has no attribute 'uid'
[2020-10-28 15:16:19,249] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/show_bookrack HTTP/1.1" 500 74843
[2020-10-28 15:16:35,918] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/novelbody/232311111 HTTP/1.1" 200 13901
[2020-10-28 15:16:37,993] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/index
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 22, in index
    liulanqi_key = cache.get('liulanqi:' + user.uid)
AttributeError: 'NoneType' object has no attribute 'uid'
[2020-10-28 15:16:38,039] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/index HTTP/1.1" 500 74955
[2020-10-28 15:16:59,156] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-10-28 15:16:59,200] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2510
[2020-10-28 15:17:08,189] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-10-28 15:17:08,203] [views.py:23] [views:index] [INFO]- 缓存中的key为：9174429218ed11eb8f5c5800e3fb0696----浏览器中的key为:9174429218ed11eb8f5c5800e3fb0696
[2020-10-28 15:17:08,266] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 17963
[2020-10-28 15:17:08,296] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/58950l_5kfSspN.jpg HTTP/1.1" 200 335654
[2020-10-28 15:17:08,300] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/58950l.jpg HTTP/1.1" 200 335654
[2020-10-28 15:17:08,333] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/banner/8797s.jpg HTTP/1.1" 200 15649
[2020-10-28 15:17:08,336] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/57304l.jpg HTTP/1.1" 200 138618
[2020-10-28 15:17:08,338] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/57840l.jpg HTTP/1.1" 200 161173
[2020-10-28 15:17:08,338] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/58950l_O9lXQZR.jpg HTTP/1.1" 200 335654
[2020-10-28 15:17:08,342] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/59178l.jpg HTTP/1.1" 200 356232
[2020-10-28 15:17:08,344] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/banner/57304l.jpg HTTP/1.1" 200 138618
[2020-10-28 15:17:10,221] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/show_bookrack
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 138, in show_bookrack
    chaptername = chapter.chaptername
AttributeError: 'NoneType' object has no attribute 'chaptername'
[2020-10-28 15:17:10,271] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/show_bookrack HTTP/1.1" 500 76438
[2020-10-28 15:17:15,796] [views.py:23] [views:index] [INFO]- 缓存中的key为：9174429218ed11eb8f5c5800e3fb0696----浏览器中的key为:9174429218ed11eb8f5c5800e3fb0696
[2020-10-28 15:17:15,859] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 17963
[2020-10-28 15:17:39,376] [views.py:23] [views:index] [INFO]- 缓存中的key为：9174429218ed11eb8f5c5800e3fb0696----浏览器中的key为:9174429218ed11eb8f5c5800e3fb0696
[2020-10-28 15:17:39,440] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 17963
[2020-10-28 15:17:40,173] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/show_bookrack
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 138, in show_bookrack
    chaptername = chapter.chaptername
AttributeError: 'NoneType' object has no attribute 'chaptername'
[2020-10-28 15:17:40,218] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/show_bookrack HTTP/1.1" 500 76438
[2020-10-28 15:23:12,603] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/show_bookrack
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 140, in show_bookrack
    chaptername = chapter.chaptername
AttributeError: 'NoneType' object has no attribute 'chaptername'
[2020-10-28 15:23:12,757] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/show_bookrack HTTP/1.1" 500 76462
[2020-10-28 15:23:27,167] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8978
[2020-10-28 15:24:15,928] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8978
[2020-10-28 15:24:38,084] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8284
[2020-10-28 15:28:10,279] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8284
[2020-10-28 15:32:37,351] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8542
[2020-10-28 15:32:38,426] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8542
[2020-10-28 15:32:39,599] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8542
[2020-10-28 15:32:42,678] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8542
[2020-10-28 15:37:01,280] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8284
[2020-10-28 15:37:19,650] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8284
[2020-10-28 15:37:20,185] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8284
[2020-10-28 15:37:47,508] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8542
[2020-10-28 15:40:59,257] [base.py:93] [base:get_response] [WARNING]- Not Found: /favicon.ico
[2020-10-28 15:40:59,258] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 2191
[2020-10-28 15:41:02,898] [base.py:93] [base:get_response] [WARNING]- Not Found: /user/index
[2020-10-28 15:41:02,899] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /user/index HTTP/1.1" 404 3310
[2020-10-28 15:44:40,472] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8314
[2020-10-28 15:44:42,770] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8314
[2020-10-28 15:47:34,498] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8248
[2020-10-28 15:47:35,391] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8248
[2020-10-28 15:47:35,665] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8248
[2020-10-28 15:49:44,025] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8248
[2020-10-28 15:49:44,761] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8248
[2020-10-28 15:49:44,996] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8248
[2020-10-28 15:49:45,194] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8248
[2020-10-28 15:57:29,965] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8248
[2020-10-28 15:57:31,029] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8248
[2020-10-28 15:57:31,930] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8248
[2020-10-28 15:58:15,303] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8248
[2020-10-28 15:58:16,670] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8248
[2020-10-28 15:58:17,460] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8248
[2020-10-28 15:58:17,999] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8248
[2020-10-28 15:59:11,086] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8248
[2020-10-28 15:59:11,587] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8248
[2020-10-28 15:59:11,774] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8248
[2020-10-28 16:15:35,264] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8306
[2020-10-28 16:17:09,631] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8314
[2020-10-28 16:24:50,853] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8314
[2020-10-28 16:24:51,560] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8314
[2020-10-28 16:25:13,209] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8314
[2020-10-28 16:27:24,572] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/show_bookrack
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 142, in show_bookrack
    return render(request, 'novel/show_bookrack.html', locals())
  File "D:\Envs\Django2020\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Envs\Django2020\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 202, in render
    .format(num_loopvars, len_item),
ValueError: Need 3 values to unpack in for loop; got 2. 
[2020-10-28 16:27:24,764] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/show_bookrack HTTP/1.1" 500 166393
[2020-10-28 16:30:53,796] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/show_bookrack
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 142, in show_bookrack
    else:
  File "D:\Envs\Django2020\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Envs\Django2020\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 202, in render
    .format(num_loopvars, len_item),
ValueError: Need 3 values to unpack in for loop; got 2. 
[2020-10-28 16:30:53,886] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/show_bookrack HTTP/1.1" 500 166165
[2020-10-28 16:30:54,805] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/show_bookrack
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 142, in show_bookrack
    else:
  File "D:\Envs\Django2020\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Envs\Django2020\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 202, in render
    .format(num_loopvars, len_item),
ValueError: Need 3 values to unpack in for loop; got 2. 
[2020-10-28 16:30:54,899] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/show_bookrack HTTP/1.1" 500 166165
[2020-10-28 16:31:12,511] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/show_bookrack
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 142, in show_bookrack
    else:
  File "D:\Envs\Django2020\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Envs\Django2020\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 202, in render
    .format(num_loopvars, len_item),
ValueError: Need 3 values to unpack in for loop; got 2. 
[2020-10-28 16:31:12,610] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/show_bookrack HTTP/1.1" 500 166319
[2020-10-28 16:31:14,688] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/show_bookrack
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 142, in show_bookrack
    else:
  File "D:\Envs\Django2020\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Envs\Django2020\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 202, in render
    .format(num_loopvars, len_item),
ValueError: Need 3 values to unpack in for loop; got 2. 
[2020-10-28 16:31:14,791] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/show_bookrack HTTP/1.1" 500 166184
[2020-10-28 17:37:30,997] [views.py:24] [views:index] [INFO]- 缓存中的key为：None----浏览器中的key为:9174429218ed11eb8f5c5800e3fb0696
[2020-10-28 17:37:31,007] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 302 0
[2020-10-28 17:37:31,042] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-10-28 17:37:31,094] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2954
[2020-10-28 17:37:39,889] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 200 4329
[2020-10-28 17:37:39,931] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2597
[2020-10-28 17:37:49,686] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-10-28 17:37:49,701] [views.py:24] [views:index] [INFO]- 缓存中的key为：33400f1c190111eba5f95800e3fb0696----浏览器中的key为:33400f1c190111eba5f95800e3fb0696
[2020-10-28 17:37:49,771] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 17963
[2020-10-28 17:37:51,404] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8591
[2020-10-28 17:38:20,312] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8591
[2020-10-28 17:38:20,845] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8591
[2020-10-28 17:38:21,039] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8591
[2020-10-28 17:38:46,690] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8351
[2020-10-28 17:38:48,956] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8351
[2020-10-28 17:39:19,987] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8591
[2020-10-28 17:39:21,371] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8591
[2020-10-28 17:39:38,605] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8591
[2020-10-28 17:39:39,089] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8591
[2020-10-28 17:39:39,290] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8591
[2020-10-28 17:39:39,470] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8591
[2020-10-28 17:40:26,092] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8297
[2020-10-28 17:40:26,800] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8297
[2020-10-28 17:40:27,012] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8297
[2020-10-28 17:40:35,534] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8363
[2020-10-28 17:40:36,687] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8363
[2020-10-28 17:41:12,247] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8297
[2020-10-28 17:41:12,889] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8297
[2020-10-28 17:41:13,099] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8297
[2020-10-28 17:41:46,215] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8314
[2020-10-28 17:42:49,526] [base.py:93] [base:get_response] [WARNING]- Not Found: /delbookcase/2718.php
[2020-10-28 17:42:49,528] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /delbookcase/2718.php HTTP/1.1" 404 2218
[2020-10-28 17:45:13,812] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8314
[2020-10-28 17:45:14,362] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8314
[2020-10-28 17:45:14,573] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8314
[2020-10-28 17:45:14,804] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8314
[2020-10-28 17:45:15,106] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8314
[2020-10-28 17:45:33,188] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8314
[2020-10-28 17:45:33,736] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8314
[2020-10-28 17:45:33,928] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8314
[2020-10-28 17:45:34,121] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8314
[2020-10-28 17:45:34,304] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8314
[2020-10-28 17:45:34,474] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8314
