[2020-10-30 14:59:28,962] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-10-30 14:59:29,048] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2372
[2020-10-30 14:59:29,207] [base.py:93] [base:get_response] [WARNING]- Not Found: /favicon.ico
[2020-10-30 14:59:29,209] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 2191
[2020-10-30 14:59:37,831] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-10-30 14:59:37,847] [views.py:24] [views:index] [INFO]- 缓存中的key为：7450859c1a7d11eba7385800e3fb0696----浏览器中的key为:7450859c1a7d11eba7385800e3fb0696
[2020-10-30 14:59:41,451] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 17963
[2020-10-30 14:59:41,474] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/58950l.jpg HTTP/1.1" 304 0
[2020-10-30 14:59:41,476] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/58950l_5kfSspN.jpg HTTP/1.1" 304 0
[2020-10-30 14:59:41,497] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/58950l_O9lXQZR.jpg HTTP/1.1" 304 0
[2020-10-30 14:59:41,502] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/57304l.jpg HTTP/1.1" 304 0
[2020-10-30 14:59:41,505] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/57840l.jpg HTTP/1.1" 304 0
[2020-10-30 14:59:41,508] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/59178l.jpg HTTP/1.1" 304 0
[2020-10-30 14:59:41,511] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/banner/8797s.jpg HTTP/1.1" 304 0
[2020-10-30 14:59:41,512] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/banner/57304l.jpg HTTP/1.1" 304 0
[2020-10-30 14:59:49,226] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7667
[2020-10-30 15:01:11,634] [views.py:24] [views:index] [INFO]- 缓存中的key为：7450859c1a7d11eba7385800e3fb0696----浏览器中的key为:7450859c1a7d11eba7385800e3fb0696
[2020-10-30 15:01:11,704] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 17963
[2020-10-30 15:01:14,324] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/11111111 HTTP/1.1" 200 7929
[2020-10-30 15:01:14,339] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/novels/8797s.jpg HTTP/1.1" 200 15649
[2020-10-30 15:01:22,933] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/add_bookrack?novelUid=11111111 HTTP/1.1" 200 17
[2020-10-30 15:01:28,302] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8385
[2020-10-30 15:04:32,244] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7667
[2020-10-30 15:04:32,776] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7667
[2020-10-30 15:04:32,961] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7667
[2020-10-30 15:04:34,170] [views.py:24] [views:index] [INFO]- 缓存中的key为：7450859c1a7d11eba7385800e3fb0696----浏览器中的key为:7450859c1a7d11eba7385800e3fb0696
[2020-10-30 15:04:34,231] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 17963
[2020-10-30 15:04:36,312] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/11111111 HTTP/1.1" 200 7929
[2020-10-30 15:04:37,883] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/add_bookrack
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view novels.views.add_bookrack didn't return an HttpResponse object. It returned None instead.
[2020-10-30 15:04:37,927] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/add_bookrack?novelUid=11111111 HTTP/1.1" 500 19910
[2020-10-30 15:04:39,709] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/add_bookrack?novelUid=11111111 HTTP/1.1" 200 17
[2020-10-30 15:04:42,064] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/add_bookrack?novelUid=11111111 HTTP/1.1" 200 17
[2020-10-30 15:04:46,319] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8385
[2020-10-30 15:05:05,621] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/121212121212 HTTP/1.1" 200 8642
[2020-10-30 15:05:05,636] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/novels/57304l.jpg HTTP/1.1" 304 0
[2020-10-30 15:05:08,857] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/novelbody/232311111 HTTP/1.1" 200 13909
[2020-10-30 15:05:10,754] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/add_chapter?chapterUid=232311111 HTTP/1.1" 200 17
[2020-10-30 15:05:13,778] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8388
[2020-10-30 15:05:28,558] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7658
[2020-10-30 15:05:30,493] [views.py:24] [views:index] [INFO]- 缓存中的key为：None----浏览器中的key为:7450859c1a7d11eba7385800e3fb0696
[2020-10-30 15:05:30,501] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 302 0
[2020-10-30 15:05:30,509] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-10-30 15:05:30,541] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2628
[2020-10-30 15:05:39,218] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 200 4329
[2020-10-30 15:05:39,252] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2678
[2020-10-30 15:05:46,778] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-10-30 15:05:46,793] [views.py:24] [views:index] [INFO]- 缓存中的key为：4bd0a0081a7e11eba7105800e3fb0696----浏览器中的key为:4bd0a0081a7e11eba7105800e3fb0696
[2020-10-30 15:05:46,861] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 17963
[2020-10-30 15:05:49,932] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/121212121212 HTTP/1.1" 200 8642
[2020-10-30 15:05:52,106] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/novelbody/333333 HTTP/1.1" 200 13516
[2020-10-30 15:05:53,887] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/add_chapter?chapterUid=333333 HTTP/1.1" 200 17
[2020-10-30 15:05:56,095] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7658
[2020-10-30 15:08:56,552] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7658
[2020-10-30 15:08:56,788] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7658
[2020-10-30 15:08:57,020] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7658
[2020-10-30 15:08:59,448] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7658
[2020-10-30 15:09:00,391] [views.py:24] [views:index] [INFO]- 缓存中的key为：4bd0a0081a7e11eba7105800e3fb0696----浏览器中的key为:4bd0a0081a7e11eba7105800e3fb0696
[2020-10-30 15:09:00,455] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 17963
[2020-10-30 15:09:04,946] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/121212121212 HTTP/1.1" 200 8642
[2020-10-30 15:09:06,796] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/novelbody/111111 HTTP/1.1" 200 13492
[2020-10-30 15:09:09,131] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/add_chapter
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 126, in add_chapter
    mybookrack_chapter.save()
AttributeError: 'QuerySet' object has no attribute 'save'
[2020-10-30 15:09:09,155] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/add_chapter?chapterUid=111111 HTTP/1.1" 500 20113
[2020-10-30 15:09:13,800] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/add_chapter
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 126, in add_chapter
    mybookrack_chapter.save()
AttributeError: 'QuerySet' object has no attribute 'save'
[2020-10-30 15:09:13,816] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/add_chapter?chapterUid=111111 HTTP/1.1" 500 20113
[2020-10-30 15:09:15,482] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/add_chapter
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 126, in add_chapter
    mybookrack_chapter.save()
AttributeError: 'QuerySet' object has no attribute 'save'
[2020-10-30 15:09:15,497] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/add_chapter?chapterUid=111111 HTTP/1.1" 500 20113
[2020-10-30 15:09:15,802] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/add_chapter
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 126, in add_chapter
    mybookrack_chapter.save()
AttributeError: 'QuerySet' object has no attribute 'save'
[2020-10-30 15:09:15,818] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/add_chapter?chapterUid=111111 HTTP/1.1" 500 20113
[2020-10-30 15:10:05,140] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/add_chapter?chapterUid=111111 HTTP/1.1" 200 17
[2020-10-30 15:10:10,347] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8385
[2020-10-30 15:10:19,990] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/121212121212 HTTP/1.1" 200 8642
[2020-10-30 15:10:21,795] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/add_bookrack?novelUid=121212121212 HTTP/1.1" 200 17
[2020-10-30 15:10:44,112] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/121212121212 HTTP/1.1" 200 8642
[2020-10-30 15:10:45,177] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/add_bookrack
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view novels.views.add_bookrack didn't return an HttpResponse object. It returned None instead.
[2020-10-30 15:10:45,192] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/add_bookrack?novelUid=121212121212 HTTP/1.1" 500 19927
[2020-10-30 15:10:48,812] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/add_bookrack?novelUid=121212121212 HTTP/1.1" 200 17
[2020-10-30 15:10:59,938] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8385
[2020-10-30 15:15:28,615] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7658
[2020-10-30 15:15:30,601] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 7658
[2020-10-30 15:15:31,797] [views.py:24] [views:index] [INFO]- 缓存中的key为：None----浏览器中的key为:4bd0a0081a7e11eba7105800e3fb0696
[2020-10-30 15:15:31,805] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 302 0
[2020-10-30 15:15:31,815] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-10-30 15:15:31,849] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2691
[2020-10-30 15:15:40,393] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-10-30 15:15:40,407] [views.py:24] [views:index] [INFO]- 缓存中的key为：b238a9ee1a7f11eb87b85800e3fb0696----浏览器中的key为:b238a9ee1a7f11eb87b85800e3fb0696
[2020-10-30 15:15:40,471] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 17963
[2020-10-30 15:15:43,315] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/121212121212 HTTP/1.1" 200 8642
[2020-10-30 15:15:45,764] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/add_bookrack
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view novels.views.add_bookrack didn't return an HttpResponse object. It returned None instead.
[2020-10-30 15:15:45,783] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/add_bookrack?novelUid=121212121212 HTTP/1.1" 500 19927
[2020-10-30 15:15:47,305] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/add_bookrack
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view novels.views.add_bookrack didn't return an HttpResponse object. It returned None instead.
[2020-10-30 15:15:47,317] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/add_bookrack?novelUid=121212121212 HTTP/1.1" 500 19927
[2020-10-30 15:15:48,790] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/add_bookrack
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view novels.views.add_bookrack didn't return an HttpResponse object. It returned None instead.
[2020-10-30 15:15:48,804] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/add_bookrack?novelUid=121212121212 HTTP/1.1" 500 19927
[2020-10-30 15:17:37,106] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/add_bookrack
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 99, in add_bookrack
    mybookrack_novel1.update(is_delete=0)
AttributeError: 'MyBookrack' object has no attribute 'update'
[2020-10-30 15:17:37,209] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/add_bookrack?novelUid=121212121212 HTTP/1.1" 500 20156
[2020-10-30 15:17:38,965] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/121212121212 HTTP/1.1" 200 8642
[2020-10-30 15:17:39,794] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/add_bookrack
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 99, in add_bookrack
    mybookrack_novel1.update(is_delete=0)
AttributeError: 'MyBookrack' object has no attribute 'update'
[2020-10-30 15:17:39,820] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/add_bookrack?novelUid=121212121212 HTTP/1.1" 500 20156
[2020-10-30 15:17:41,113] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/add_bookrack
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 99, in add_bookrack
    mybookrack_novel1.update(is_delete=0)
AttributeError: 'MyBookrack' object has no attribute 'update'
[2020-10-30 15:17:41,128] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/add_bookrack?novelUid=121212121212 HTTP/1.1" 500 20156
[2020-10-30 15:17:41,348] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/add_bookrack
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\novels\views.py", line 99, in add_bookrack
    mybookrack_novel1.update(is_delete=0)
AttributeError: 'MyBookrack' object has no attribute 'update'
[2020-10-30 15:17:41,365] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/add_bookrack?novelUid=121212121212 HTTP/1.1" 500 20156
[2020-10-30 15:18:16,163] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/detail/121212121212 HTTP/1.1" 200 8642
[2020-10-30 15:18:16,698] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /novels/add_bookrack
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view novels.views.add_bookrack didn't return an HttpResponse object. It returned None instead.
[2020-10-30 15:18:16,712] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /novels/add_bookrack?novelUid=121212121212 HTTP/1.1" 500 19926
[2020-10-30 15:18:17,890] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/add_bookrack?novelUid=121212121212 HTTP/1.1" 200 17
[2020-10-30 15:18:20,585] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8385
[2020-10-30 15:18:54,236] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8385
[2020-10-30 15:20:31,562] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8385
[2020-10-30 15:20:33,107] [views.py:24] [views:index] [INFO]- 缓存中的key为：b238a9ee1a7f11eb87b85800e3fb0696----浏览器中的key为:b238a9ee1a7f11eb87b85800e3fb0696
[2020-10-30 15:20:33,171] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 17963
[2020-10-30 15:20:39,114] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/show_bookrack HTTP/1.1" 200 8385
[2020-10-30 15:20:43,597] [views.py:24] [views:index] [INFO]- 缓存中的key为：None----浏览器中的key为:b238a9ee1a7f11eb87b85800e3fb0696
[2020-10-30 15:20:43,604] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 302 0
[2020-10-30 15:20:43,613] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-10-30 15:20:43,646] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2556
[2020-10-30 15:20:51,943] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw?ran=0.19785375614152168 HTTP/1.1" 200 2572
[2020-10-30 15:20:57,255] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-10-30 15:20:57,269] [views.py:24] [views:index] [INFO]- 缓存中的key为：6c1137221a8011ebbcd65800e3fb0696----浏览器中的key为:6c1137221a8011ebbcd65800e3fb0696
[2020-10-30 15:20:57,331] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 17963
[2020-10-30 15:21:06,500] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /novels/search HTTP/1.1" 200 7376
[2020-10-30 15:21:48,550] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /novels/search HTTP/1.1" 200 7384
[2020-10-30 15:21:52,683] [views.py:24] [views:index] [INFO]- 缓存中的key为：6c1137221a8011ebbcd65800e3fb0696----浏览器中的key为:6c1137221a8011ebbcd65800e3fb0696
[2020-10-30 15:21:52,745] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 17963
[2020-10-30 15:35:36,137] [views.py:24] [views:index] [INFO]- 缓存中的key为：None----浏览器中的key为:6c1137221a8011ebbcd65800e3fb0696
[2020-10-30 15:35:36,154] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 302 0
[2020-10-30 15:35:36,170] [exception.py:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /user/login
Traceback (most recent call last):
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Envs\Django2020\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\xinxi\PycharmProjects\Qinxiangshuge\user\views.py", line 64, in user_login
    response = render(request, 'user/login.html', {'user': username})
  File "D:\Envs\Django2020\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Envs\Django2020\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template_name, skip=history,
  File "D:\Envs\Django2020\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "D:\Envs\Django2020\lib\site-packages\django\template\loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "D:\Envs\Django2020\lib\site-packages\django\template\defaulttags.py", line 815, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 454, in parse
    raise self.error(token, e)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 452, in parse
    filter_expression = self.compile_filter(token.contents)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 568, in compile_filter
    return FilterExpression(token, self)
  File "D:\Envs\Django2020\lib\site-packages\django\template\base.py", line 668, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' typename' from 'type. typename'
[2020-10-30 15:35:36,469] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /user/login HTTP/1.1" 500 204129
[2020-10-30 15:36:58,076] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-10-30 15:36:58,120] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2863
[2020-10-30 15:37:06,403] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-10-30 15:37:06,421] [views.py:24] [views:index] [INFO]- 缓存中的key为：b0e46b9c1a8211eba5495800e3fb0696----浏览器中的key为:b0e46b9c1a8211eba5495800e3fb0696
[2020-10-30 15:37:06,490] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 19116
[2020-10-30 15:37:27,711] [views.py:24] [views:index] [INFO]- 缓存中的key为：b0e46b9c1a8211eba5495800e3fb0696----浏览器中的key为:b0e46b9c1a8211eba5495800e3fb0696
[2020-10-30 15:37:27,784] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 18166
[2020-10-30 15:37:29,640] [views.py:24] [views:index] [INFO]- 缓存中的key为：b0e46b9c1a8211eba5495800e3fb0696----浏览器中的key为:b0e46b9c1a8211eba5495800e3fb0696
[2020-10-30 15:37:29,709] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 18166
[2020-10-30 15:39:26,041] [views.py:24] [views:index] [INFO]- 缓存中的key为：b0e46b9c1a8211eba5495800e3fb0696----浏览器中的key为:b0e46b9c1a8211eba5495800e3fb0696
[2020-10-30 15:39:26,110] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 18298
[2020-10-30 15:39:27,181] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/1 HTTP/1.1" 200 4046
[2020-10-30 15:39:39,930] [views.py:24] [views:index] [INFO]- 缓存中的key为：b0e46b9c1a8211eba5495800e3fb0696----浏览器中的key为:b0e46b9c1a8211eba5495800e3fb0696
[2020-10-30 15:39:39,994] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 18298
[2020-10-30 15:39:41,235] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/2 HTTP/1.1" 200 4046
[2020-10-30 15:40:16,951] [views.py:24] [views:index] [INFO]- 缓存中的key为：b0e46b9c1a8211eba5495800e3fb0696----浏览器中的key为:b0e46b9c1a8211eba5495800e3fb0696
[2020-10-30 15:40:17,023] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 18298
[2020-10-30 15:40:18,144] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/1 HTTP/1.1" 200 4040
[2020-10-30 15:40:20,555] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/2 HTTP/1.1" 200 4040
[2020-10-30 15:42:11,890] [views.py:24] [views:index] [INFO]- 缓存中的key为：None----浏览器中的key为:b0e46b9c1a8211eba5495800e3fb0696
[2020-10-30 15:42:11,909] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 302 0
[2020-10-30 15:42:11,928] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-10-30 15:42:11,963] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2979
[2020-10-30 15:42:20,818] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-10-30 15:42:20,833] [views.py:24] [views:index] [INFO]- 缓存中的key为：6bf656461a8311eba58d5800e3fb0696----浏览器中的key为:6bf656461a8311eba58d5800e3fb0696
[2020-10-30 15:42:20,978] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 18298
[2020-10-30 15:42:22,071] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/1 HTTP/1.1" 200 4040
[2020-10-30 15:43:49,179] [views.py:24] [views:index] [INFO]- 缓存中的key为：6bf656461a8311eba58d5800e3fb0696----浏览器中的key为:6bf656461a8311eba58d5800e3fb0696
[2020-10-30 15:43:49,370] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 18298
[2020-10-30 15:43:51,277] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/1 HTTP/1.1" 200 4046
[2020-10-30 15:43:54,013] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/2 HTTP/1.1" 200 4046
[2020-10-30 15:44:06,926] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/1 HTTP/1.1" 200 4046
[2020-10-30 15:48:08,802] [views.py:24] [views:index] [INFO]- 缓存中的key为：None----浏览器中的key为:6bf656461a8311eba58d5800e3fb0696
[2020-10-30 15:48:08,810] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 302 0
[2020-10-30 15:48:08,822] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-10-30 15:48:08,852] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2795
[2020-10-30 15:48:18,771] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-10-30 15:48:18,786] [views.py:24] [views:index] [INFO]- 缓存中的key为：40b011a41a8411eba9e55800e3fb0696----浏览器中的key为:40b011a41a8411eba9e55800e3fb0696
[2020-10-30 15:48:18,850] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 18298
[2020-10-30 15:48:20,407] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/1 HTTP/1.1" 200 5459
[2020-10-30 15:48:20,429] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/novels/57840l.jpg HTTP/1.1" 200 161173
[2020-10-30 15:49:27,000] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/1 HTTP/1.1" 200 5543
[2020-10-30 15:51:56,006] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/login HTTP/1.1" 200 4227
[2020-10-30 15:51:56,075] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw HTTP/1.1" 200 2540
[2020-10-30 15:52:03,143] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /user/draw?ran=0.7369957009368007 HTTP/1.1" 200 2554
[2020-10-30 15:52:07,355] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /user/login HTTP/1.1" 302 0
[2020-10-30 15:52:07,369] [views.py:24] [views:index] [INFO]- 缓存中的key为：c8196f5e1a8411eb91fb5800e3fb0696----浏览器中的key为:c8196f5e1a8411eb91fb5800e3fb0696
[2020-10-30 15:52:07,433] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 18298
[2020-10-30 15:52:07,483] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/58950l.jpg HTTP/1.1" 200 335654
[2020-10-30 15:52:07,485] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/58950l_5kfSspN.jpg HTTP/1.1" 200 335654
[2020-10-30 15:52:07,526] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/58950l_O9lXQZR.jpg HTTP/1.1" 200 335654
[2020-10-30 15:52:07,532] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/57304l.jpg HTTP/1.1" 200 138618
[2020-10-30 15:52:07,564] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/57840l.jpg HTTP/1.1" 200 161173
[2020-10-30 15:52:07,567] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/banner/8797s.jpg HTTP/1.1" 200 15649
[2020-10-30 15:52:07,569] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/type/59178l.jpg HTTP/1.1" 200 356232
[2020-10-30 15:52:07,574] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/banner/57304l.jpg HTTP/1.1" 200 138618
[2020-10-30 15:52:12,555] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/1 HTTP/1.1" 200 5143
[2020-10-30 15:52:15,858] [views.py:24] [views:index] [INFO]- 缓存中的key为：c8196f5e1a8411eb91fb5800e3fb0696----浏览器中的key为:c8196f5e1a8411eb91fb5800e3fb0696
[2020-10-30 15:52:15,924] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/index HTTP/1.1" 200 18298
[2020-10-30 15:52:17,843] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/1 HTTP/1.1" 200 5143
[2020-10-30 15:52:24,073] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/4 HTTP/1.1" 200 3680
[2020-10-30 15:52:24,095] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/novels/111s_YM8x2d4.jpg HTTP/1.1" 200 13525
[2020-10-30 15:52:28,209] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/5 HTTP/1.1" 200 3712
[2020-10-30 15:52:28,235] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/media/novels/57304l_0H2be4N.jpg HTTP/1.1" 200 138618
[2020-10-30 15:52:33,291] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/5 HTTP/1.1" 200 3712
[2020-10-30 16:23:02,669] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /novels/category_show/1 HTTP/1.1" 200 5143
